import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// app/layout.js
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav className="border-b w-full">
            <div className="flex justify-between h-16 items-center px-4 w-full">
              <div className="flex justify-between">
                <Link href="/" className="mr-6 flex items-center space-x-2">
                  <span className="text-xl font-bold">TaskMaster</span>
                </Link>
                <div className="hidden md:flex items-center  space-x-4 lg:space-x-6 flex-1">
                  <Link
                    className="hover:bg-white hover:text-black px-2 py-4 rounded"
                    href="/dashboard"
                  >
                    Dashboard
                  </Link>
                </div>
              </div>
            </div>
          </nav>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
